sudo: required
dist: trusty

os:
  - windows
  - linux
  - osx

language: cpp

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - cmake --build .

after_script:
  - cmake --build . --target riku_test